### ISSUE TITLE
Remove version check workaround

### ISSUE THREAD

**Issue by Andy-Grigg** [ansys/grantami-recordlists#201]
The additional check [here](https://github.com/ansys/grantami-recordlists/blob/b4b458c8f1328649cf4ddd0057ab51688339e47a/src/ansys/grantami/recordlists/_connection.py#L655) can be removed, because now all 'specific-version' record list items will always have a record guid.

**Comment by ludovicsteinbach** [comment]
@Andy-Grigg  I just had a look at this. I don't think we can remove the check. For a draft v2, superseding a released v1, list item defined with record_version=2:
- The item has a `record_guid` for the admin user
- The item does not have a `record_guid` for a list user. Which means the resolvability check still queries the full history and if we then don't check for the specific version, we'll get false positives.

Is that what you would expect? I think it sort of makes sense: read users can't see draft records, therefore can't get their record guids.

**Comment by Andy-Grigg** [comment]
Well, there's three scenarios within the scenario you describe:

* If the list item doesn't have a version specified, I'd expect RL to return just the history guid, which we can resolve
* If the list item has v1 specified, RL should return the v1 record guid which we can resolve
* If the list item has v2 specified and RL returns no guid (makes sense because as you say, the user can't see the record), and so we should then return a negative result, i.e. don't include the record in the resulting list

Does the check for the final scenario become: "If the record list item contains a record version but no record guid, discard"?

**Comment by Andy-Grigg** [comment]
After discussion, we're going to leave the code as is. The check described above

> Does the check for the final scenario become: "If the record list item contains a record version but no record guid, discard"?

Would work, and would reduce the number of calls required to the database, but only in the specific scenario described above. The trade off is that it feels like a more fragile scenario: if the record guid is missing for any other reason, we'll end up with a false negative, and we can't be certain that this is the only reason the record guid would be missing.
